export {Home} from "./Home"
export {Error} from "./Error"
export {ProductDetails} from "./ProductDetails"
export {Register} from "./Register"
export {Login} from "./Login"
export {DashboardAdmin} from "./admin/DashboardAdmin"
export {Categories} from "./admin/Categories"
export {Orders} from "./admin/Orders"
export {Users} from "./admin/Users"
export {Products} from "./admin/Products"
export {DashboardUser} from "./user/DashboardUser"
export {UserProfile} from "./user/UserProfile"
export {UserOrders} from "./user/UserOrders"

