export {Home} from "./Home"
export {Error} from "./Error"
export {ProductDetails} from "./ProductDetails"
export {Register} from "./Register"
export {Login} from "./Login"
export {DashboardAdmin} from "./admin/DashboardAdmin"
export {Orders} from "../components/Orders"
export {AdminUserManagement} from "../components/AdminUserManagement"
export {AdminProducts} from "../components/AdminProducts"
export {DashboardUser} from "./user/DashboardUser"
export {UserProfile} from "./user/UserProfile"
export {UserOrders} from "./user/UserOrders"

