export {Home} from "./Home"
export {Error} from "./Error"
export {ProductDetails} from "./ProductDetails"
export {Register} from "./Register"
export {Login} from "./Login"
export {Cart} from "./Cart"
export {DashboardAdmin} from "./admin/DashboardAdmin"
export {AdminOrders} from "../components/AdminOrders"
export {AdminUserManagement} from "../components/AdminUserManagement"
export {AdminProducts} from "../components/AdminProducts"
export {AdminCategories} from "../components/AdminCategories"
export {DashboardUser} from "./user/DashboardUser"
export {UserProfile} from "./user/UserProfile"


